---
language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - 'pypy'

install:
  - 'pip install -r requirements.txt -r requirements-dev.txt'
  - 'pip install .'

script:
  - 'flake8 pydas'
