---
language: python

sudo: false

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - 'pypy'

matrix:
  fast_finish: true

  allow_failures:
    - python: 'pypy'

cache:
  directories:
    - '$HOME/.cache/pip'

install:
  - 'pip install -U pip'
  - 'pip -V'
  - 'pip install -U -r requirements.txt -r requirements-dev.txt'
  - 'pip install -U .'

script:
  - 'flake8 pydas'
